### PR TITLE
Figure style changes and TOC

### LINKED ISSUE #39: adding table of content
Tom will try to add this automatically

### PR DESCRIPTION
**Pull request by tomhull**
Two major changes

1. i've changed how figures are rendered to using the figure format, this means they are a) centred, and b) automatically numbered and can be referenced in the text with a easy hyperlink.
The bad is that the caption doesn't render in the markdown preview, only in the raw text or PDF. Happy to revert back if needed.

2. added a automatic table of contents (closes #39), this can be adjusted if we don't want to have as many subsections.
The easiest way of getting the author list (which I also tided up) to appear first was to put it into the preamble.
Oh and I also cropped the logo to look a bit nicer.

### CODE REVIEW

**Review by soerenthomsen — APPROVED** [review]
Thanks Tom. I will approve and check how the figures look in the markdown afterwards.

**Comment by soerenthomsen** [comment]
so should we link the reader to the pdf then? not really nice or?

**Comment by tomhull** [comment]
If I can get the HTML version working nicely that would be a better option
I think for reading

**Comment by soerenthomsen** [comment]
Yeah I think we need one version which is nice to read online. as I mention in my email @jbusecke was interested in supporting us on this.

**Pull request merged**
