### PR TITLE
adding Stuart Pearce authorship and contributions

### PR DESCRIPTION
**Pull request by soerenthomsen**
adding @s-pearce authorship and contributions

### CODE REVIEW

**Comment by soerenthomsen** [comment]
@s-pearce could you add your correct affiliation directly to the file?

**Review by patricialg — APPROVED** [review]
@s-pearce please, remember to add you affiliation :)

**Review by s-pearce — APPROVED** [review]

**Comment by s-pearce** [comment]
Thanks @patricialg and @soerenthomsen, I was out for a few days so thanks for putting my name in there and starting a section.  I will start a new pull request with my information filled out.
Stuart

**Comment by soerenthomsen** [comment]
Ok yes please go ahead @s-pearce and start a new pull-request as like this you are also listed in the repo as contributor! Thanks

**Pull request merged**
