### PR TITLE
WIP: Better reference labels

### PR DESCRIPTION
**Pull request by jbusecke**
Towards #88

### CODE REVIEW

**Comment by soerenthomsen** [comment]
Thanks @jbusecke as the test runs not through I am not sure how to proceed.

**Comment by jbusecke** [comment]
Yeah this was just an unsuccessful attempt. I should have made it a draft in the first place. Please ignore for now, Ill ping you when this is working.

**Comment by soerenthomsen** [comment]
Hi @jbusecke, happy to support this PR to try to fix this possibly this week to close the community review towards end of January. Will read the Sphinx communication and the issues you shared. Let's get this done!

**Comment by soerenthomsen** [comment]
Could it be a problem that we don't create a `conf.py` file?
https://sphinx-astrorefs.readthedocs.io/en/latest/?badge=latest

**Comment by soerenthomsen** [comment]
Hi @jbusecke, we are close to submit the first version of this SOP to the OBPS. Should we give it a last try to make the references look nicer? I am available for a call to coordinate.

**Comment by jbusecke** [comment]
Can we wait with that until after OSM? I am pretty packed with stuff this week? Next week Id be happy to take look.

**Comment by jbusecke** [comment]
Superseeded by #216

**Pull request closed without merging**
