### PR TITLE
content: rewriting of "recommended corrections"

### PR DESCRIPTION
**Pull request by soerenthomsen**
@tomhull, @cgourcuf, @patricialg  could you review my implementation of your suggestions. 

This addresses: #238

FYI @vturpin

### CODE REVIEW

**Comment by cgourcuf** [comment]
Hi @soerenthomsen I reviewed the text, it is OK for me, thanks! Sorry but I do not see how to proceed further apart from sending you this comment...

**Comment by soerenthomsen** [comment]
Hi @cgourcuf, thanks a lot. To perform an official review you click on "Files changed" at the top bar ->  "review changes" -> - [ ] Comment
Submit general feedback without explicit approval.

- [ ] Approve
Submit feedback and approve merging these changes.

- [ ] Request changes
Submit feedback that must be addressed before merging.

**Comment by soerenthomsen** [comment]
@tomhull could you have a check too and merge if you are fine?

**Review by tomhull — APPROVED** [review]
Sure

**Pull request merged**
